spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://koc-user-db:3306/theme?serverTimezone=Asia/Seoul
    username: root
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

springdoc:
  version: '1.0.0'
  api-docs:
    path: /api-docs
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: method

sql:
  init:
    platporm: mysql
    data-locations: classpath:data.sql

social-login:
  kakao:
    client_id: "350e38b3eb9c43bd8f47ce44d19ef349"
    redirect_uri: "http://localhost:8080/auth"
    oauth_uri: "https://kauth.kakao.com/oauth"
    kapi_user_info_uri: "https://kapi.kakao.com/v2/user/me"
    javascript_key: "819d78cdd08a6a1d4652bc9f5806bf20"





